name: Release
on:
  push:
    tags:
      - 'v[0-9].*'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v3
      - name: Build and push
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker buildx create --use
          docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/i386,linux/amd64 --tag "${{ secrets.DOCKER_HUB_USERNAME }}/balance:$(git describe --tags)" --build-arg VERSION=$(git describe --tags | tr -d v) . --push
